#page title
page_title                                :                                         # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1532894165                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             : https://apps.apple.com/app/apple-store/id1532894165?pt=869040&ct=landing&mt=8# Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  :                       # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Create beautiful icons and personalize your home screen like never before!

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Alexey Plekhanov                                
your_link                                 : https://apps.apple.com/us/developer/alexey-plekhanov/id543015684
your_city                                 :                                
email_address                             : mail@aplekhanov.com
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : alexeyplekhanov
github_username                           : aplekhanov
youtube_username                          : 



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Colors
    description                           : Hundreds of beautiful colors
    fontawesome_icon_name                 : brush 

  - title                                 : Glyphs
    description                           : Over 2000 system glyphs
    fontawesome_icon_name                 : mobile 

  - title                                 : Emoji & Text
    description                           : Turn any emoji or a word into an icon
    fontawesome_icon_name                 : smile 


# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.jpg                    # Replace with alternative image path or image URL.
cover_overlay_color                       : 
cover_overlay_transparency                : 

device_color                              : blue                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#007aff"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#333333"

feature_icons_foreground_color            : "#ffffff"
feature_icons_background_color            : "#007aff"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME
  - landing.png

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
